version: '3'
services: 
  app:
    container_name: docker-node-app
    restart: always
    build: ./api
    ports:
      - '3001:3001'
    links:
      - mongo
    
    entrypoint: npm start
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"
  web:
    container_name: angular
    build: ./SPA
    restart: always
    ports:
      - 4200:4200
      - '49153:49153'
    links: 
      - app
    
    entrypoint: ng serve --host 0.0.0.0 --poll 1
  python:
    container_name: web_scraper
    build: ./web_scraper
    links: 
      - mongo
    