version: '2'
services: 
    app:
        restart: always
        build:
          context: .
          dockerfile: Dockerfile
        image: angular-image
        volumes:
          - .\:/usr/src/app
        ports:
          - '4200:4200'
          - '49153:49153'
        
#volumes:
  #app-unison-sync:
    #external: true
